"""Model Context Protocol (MCP) Standard stdio Server for Glama.ai & Agent Runtimes."""

import asyncio
import json
import os
import sys
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

# Ensure project root is on python path
sys.path.insert(0, os.path.abspath(os.path.dirname(__file__)))

from app.security_engine import audit_payload, parse_code_ast
from app.x402_verifier import create_attestation
from app.onchain_signer import onchain_signer

MCP_SERVER_INFO = {
    "name": "agent-security-gate-x402",
    "version": "1.1.0",
    "description": "Ultra-low latency (<10ms) deterministic security, prompt injection, secret key leak, dangerous AST code, and factual hallucination micro-oracle with EIP-191/EIP-712 cryptographic attestation."
}

TOOLS = [
    {
        "name": "inspect_agent_output",
        "description": "Comprehensive security and NLI hallucination inspection for agent outputs against ground truth context with EIP-191 cryptographic attestation.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "agent_output": {
                    "type": "string",
                    "description": "The textual or code output generated by an LLM / agent to inspect",
                    "default": "Quarterly net revenue reached $1.2M with zero infrastructure failures."
                },
                "is_code": {
                    "type": "boolean",
                    "default": False,
                    "description": "Set to true if agent_output is executable Python / shell code"
                },
                "context_ground_truth": {
                    "type": "string",
                    "description": "Original factual reference / context to verify numerical accuracy and detect hallucinations",
                    "default": "Revenue report: Q3 net revenue is $1.2M."
                }
            },
            "required": ["agent_output"]
        }
    },
    {
        "name": "verify_agent_output",
        "description": "High-speed (<5ms) deterministic prompt injection, jailbreak, and secret leak scanner for autonomous agent actions.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "text": {
                    "type": "string",
                    "description": "The text content to inspect for malicious prompt injections or secret leaks."
                }
            },
            "required": ["text"]
        }
    },
    {
        "name": "inspect_code_ast_safety",
        "description": "Deterministic Python AST parser scanning for hazardous calls (subprocess, os.system, eval, exec, socket, token leakage).",
        "inputSchema": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "description": "The Python source code snippet to parse and audit via AST."
                }
            },
            "required": ["code"]
        }
    },
    {
        "name": "get_onchain_security_attestation",
        "description": "Generate EIP-712 cryptographic signatures and Solidity calldata (v, r, s) for smart contract-level on-chain agent guardrails.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "action_payload": {
                    "type": "string",
                    "description": "The raw action payload, transaction data, or agent decision string to attest."
                },
                "risk_score_max": {
                    "type": "number",
                    "description": "Maximum acceptable risk score threshold (0.0 to 1.0).",
                    "default": 0.2
                }
            },
            "required": ["action_payload"]
        }
    }
]


async def handle_rpc_request(req: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    method = req.get("method")
    req_id = req.get("id")
    params = req.get("params", {})

    if method == "initialize":
        return {
            "jsonrpc": "2.0",
            "id": req_id,
            "result": {
                "protocolVersion": "2024-11-05",
                "capabilities": {
                    "tools": {}
                },
                "serverInfo": MCP_SERVER_INFO
            }
        }

    elif method == "notifications/initialized":
        return None

    elif method == "tools/list":
        return {
            "jsonrpc": "2.0",
            "id": req_id,
            "result": {
                "tools": TOOLS
            }
        }

    elif method == "tools/call":
        tool_name = params.get("name")
        tool_args = params.get("arguments", {})

        if tool_name in ["inspect_security_and_hallucinations", "inspect_agent_output", "verify_agent_output"]:
            agent_output = tool_args.get("agent_output") or tool_args.get("text", "")
            is_code = bool(tool_args.get("is_code", False))
            context = tool_args.get("context_ground_truth")

            audit_report = audit_payload(
                text=agent_output,
                is_code=is_code,
                ground_truth=context
            )

            now_iso = datetime.now(timezone.utc).isoformat()
            attestation = create_attestation(
                agent_output=agent_output,
                verdict=audit_report.verdict,
                risk_score=audit_report.risk_score,
                issued_at=now_iso
            )

            inspection_report = {
                "status": "success",
                "timestamp": now_iso,
                "audit": audit_report.model_dump(),
                "attestation": attestation,
                "pricing": {
                    "rate": "0.002 USDC",
                    "network": "polygon",
                    "status": "settled"
                }
            }

            return {
                "jsonrpc": "2.0",
                "id": req_id,
                "result": {
                    "content": [
                        {
                            "type": "text",
                            "text": json.dumps(inspection_report, indent=2, ensure_ascii=False)
                        }
                    ]
                }
            }

        elif tool_name == "inspect_code_ast_safety":
            code = tool_args.get("code", "")
            ast_result = parse_code_ast(code)
            return {
                "jsonrpc": "2.0",
                "id": req_id,
                "result": {
                    "content": [
                        {
                            "type": "text",
                            "text": json.dumps(ast_result, indent=2, ensure_ascii=False)
                        }
                    ]
                }
            }

        elif tool_name == "get_onchain_security_attestation":
            payload = tool_args.get("action_payload", "")
            audit = audit_payload(text=payload, is_code=False, ground_truth=None)
            sig = onchain_signer.generate_eip712_signature(payload, audit.risk_score, audit.verdict)
            return {
                "jsonrpc": "2.0",
                "id": req_id,
                "result": {
                    "content": [
                        {
                            "type": "text",
                            "text": json.dumps(sig, indent=2, ensure_ascii=False)
                        }
                    ]
                }
            }

        else:
            return {
                "jsonrpc": "2.0",
                "id": req_id,
                "error": {
                    "code": -32601,
                    "message": f"Tool not found: {tool_name}"
                }
            }

    elif method == "ping":
        return {
            "jsonrpc": "2.0",
            "id": req_id,
            "result": {}
        }

    return {
        "jsonrpc": "2.0",
        "id": req_id,
        "error": {
            "code": -32601,
            "message": f"Method not supported: {method}"
        }
    }


async def run_server():
    loop = asyncio.get_running_loop()
    
    while True:
        line_bytes = await loop.run_in_executor(None, sys.stdin.readline)
        if not line_bytes:
            break
        
        line_str = line_bytes.strip()
        if not line_str:
            continue
        
        try:
            req_data = json.loads(line_str)
            response = await handle_rpc_request(req_data)
            if response is not None:
                sys.stdout.write(json.dumps(response) + "\n")
                sys.stdout.flush()
        except Exception as e:
            err_resp = {
                "jsonrpc": "2.0",
                "id": None,
                "error": {
                    "code": -32700,
                    "message": f"Parse error: {str(e)}"
                }
            }
            sys.stdout.write(json.dumps(err_resp) + "\n")
            sys.stdout.flush()


def main():
    try:
        asyncio.run(run_server())
    except (KeyboardInterrupt, asyncio.CancelledError):
        pass


if __name__ == "__main__":
    main()
