"""
Comprehensive Unit & Integration Test Suite for:
1. Zero-Liability Audit Proof & EIP-191 Cryptographic Receipts (Server-side)
2. BoundedAgentWallet Spend Guardrails & Persistence (Client-side)
"""

import json
import os
import tempfile
import pytest
from eth_account import Account
from eth_account.messages import encode_defunct
from fastapi.testclient import TestClient

from app.main import app
from app.x402_verifier import generate_audit_proof
from sdk.agent_gate_sdk import (
    BoundedAgentWallet,
    BudgetExceededError,
    SecurityGateClient
)


@pytest.fixture
def test_client():
    return TestClient(app)


class TestZeroLiabilityAuditProof:
    """Tests cryptographic validity of the Zero-Liability Audit Proof generated by the Sheriff Gate."""

    def test_audit_proof_cryptographic_signature(self):
        payload = "def execute_order(): pass"
        verdict = "PASSED"
        risk_score = 0.0

        proof = generate_audit_proof(
            payload_text=payload,
            verdict=verdict,
            risk_score=risk_score,
            caller_address="0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
        )

        assert proof["proof_hash"].startswith("0x")
        assert proof["terms"] == "ZERO_LIABILITY_AS_IS_PROVENANCE_V1"
        assert "headers" in proof
        assert "X-Sheriff-Audit-Proof" in proof["headers"]
        assert "X-Sheriff-Signature" in proof["headers"]

        # Mathematically verify EIP-191 signature matches issuer
        issuer = proof["issuer"]
        signature = proof["signature"]
        proof_hash = proof["proof_hash"]

        msg = encode_defunct(text=f"SHERIFF-AUDIT-PROOF:{proof_hash}")
        recovered_address = Account.recover_message(msg, signature=signature)
        assert recovered_address.lower() == issuer.lower()

    def test_inspect_endpoint_serves_audit_proof_and_headers(self, test_client):
        payload = {
            "agent_output": "The current price of Bitcoin is $85,000.",
            "is_code": False
        }
        resp = test_client.post("/api/v1/inspect", json=payload)
        assert resp.status_code == 200

        # Verify Response Headers
        assert "x-sheriff-audit-proof" in resp.headers
        assert "x-sheriff-signature" in resp.headers
        assert resp.headers.get("x-sheriff-terms") == "ZERO_LIABILITY_AS_IS_PROVENANCE_V1"
        assert resp.headers.get("x-sheriff-terms-url") == "/api/v1/terms"

        # Verify Response JSON Body
        data = resp.json()
        assert "audit_proof" in data
        assert data["audit_proof"]["proof_hash"] == resp.headers["x-sheriff-audit-proof"]
        assert data["audit_proof"]["signature"] == resp.headers["x-sheriff-signature"]
        assert data["audit_proof"]["terms"] == "ZERO_LIABILITY_AS_IS_PROVENANCE_V1"
        assert data["audit_proof"]["terms_url"] == "/api/v1/terms"

    def test_terms_endpoint_json(self, test_client):
        for endpoint in ["/api/v1/terms", "/terms"]:
            resp = test_client.get(endpoint)
            assert resp.status_code == 200
            data = resp.json()
            assert data["terms_identifier"] == "ZERO_LIABILITY_AS_IS_PROVENANCE_V1"
            assert data["liability_cap_usd"] == 50.0
            assert "canonical_terms_sha256" in data
            assert len(data["canonical_terms_sha256"]) == 64
            assert "as_is" in data["summary"]
            assert "limitation_of_liability" in data["summary"]
            assert data["status"] == "active"

    def test_terms_endpoint_raw_markdown(self, test_client):
        resp = test_client.get("/api/v1/terms?format=raw")
        assert resp.status_code == 200
        assert "ZERO_LIABILITY_AS_IS_PROVENANCE_V1" in resp.text
        assert resp.headers.get("x-sheriff-terms") == "ZERO_LIABILITY_AS_IS_PROVENANCE_V1"
        assert "markdown" in resp.headers.get("content-type", "")



class TestBoundedAgentWalletGuardrails:
    """Tests client-side spend limits, whitelist enforcement, and persistence."""

    def test_whitelist_rejection(self):
        wallet = BoundedAgentWallet(
            daily_limit_usdc=1.0,
            per_tx_limit_usdc=0.05,
            whitelist=["0x255F9991233f86B29dB847c8d5b8CB9915e80dCf"]
        )

        allowed, reason = wallet.can_pay("0x9999999999999999999999999999999999999999", 0.002)
        assert not allowed
        assert "not in authorized whitelist" in reason

        allowed_gate, _ = wallet.can_pay("0x255F9991233f86B29dB847c8d5b8CB9915e80dCf", 0.002)
        assert allowed_gate

    def test_per_tx_limit_enforcement(self):
        wallet = BoundedAgentWallet(
            daily_limit_usdc=1.0,
            per_tx_limit_usdc=0.005,  # Max 0.005 USDC per call
            whitelist=["0x255F9991233f86B29dB847c8d5b8CB9915e80dCf"]
        )

        allowed, reason = wallet.can_pay("0x255F9991233f86B29dB847c8d5b8CB9915e80dCf", 0.01)
        assert not allowed
        assert "exceeds per-transaction limit" in reason

    def test_daily_budget_limit_accumulation(self):
        wallet = BoundedAgentWallet(
            daily_limit_usdc=0.005,
            per_tx_limit_usdc=0.005,
            whitelist=["0x255F9991233f86B29dB847c8d5b8CB9915e80dCf"]
        )

        # 1st spend: 0.003
        allowed1, _ = wallet.can_pay("0x255F9991233f86B29dB847c8d5b8CB9915e80dCf", 0.003)
        assert allowed1
        wallet.record_spend("0x255F9991233f86B29dB847c8d5b8CB9915e80dCf", 0.003)
        assert wallet.get_daily_spent() == 0.003

        # 2nd spend: 0.003 -> Should exceed 0.005 daily limit
        allowed2, reason2 = wallet.can_pay("0x255F9991233f86B29dB847c8d5b8CB9915e80dCf", 0.003)
        assert not allowed2
        assert "Daily limit reached" in reason2

    def test_ledger_persistence_across_restarts(self):
        with tempfile.NamedTemporaryFile(suffix=".json", delete=False) as tf:
            ledger_file = tf.name

        try:
            # Instance 1: spends 0.004 USDC
            w1 = BoundedAgentWallet(
                daily_limit_usdc=1.0,
                per_tx_limit_usdc=0.05,
                ledger_path=ledger_file
            )
            w1.record_spend(
                recipient="0x255F9991233f86B29dB847c8d5b8CB9915e80dCf",
                amount_usdc=0.004,
                audit_proof="0xabc123"
            )
            assert w1.get_daily_spent() == 0.004

            # Instance 2 (Simulating reboot): recovers ledger from disk
            w2 = BoundedAgentWallet(
                daily_limit_usdc=1.0,
                per_tx_limit_usdc=0.05,
                ledger_path=ledger_file
            )
            assert w2.get_daily_spent() == 0.004
            assert len(w2.in_memory_records) == 1
            assert w2.in_memory_records[0]["audit_proof"] == "0xabc123"

        finally:
            if os.path.exists(ledger_file):
                os.remove(ledger_file)

    def test_sdk_client_integration_with_bounded_wallet(self):
        wallet = BoundedAgentWallet(
            daily_limit_usdc=0.001,  # Lower than inspection cost (0.002)
            per_tx_limit_usdc=0.01
        )
        client = SecurityGateClient(
            app=app,
            bounded_wallet=wallet
        )

        with pytest.raises(BudgetExceededError) as exc_info:
            client.inspect("Sanity test output")

        assert "Autonomous inspection blocked by client BoundedAgentWallet" in str(exc_info.value)
